name: 定时运行

on:
  workflow_dispatch:
  schedule:
    - cron: '30 12/18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install dependencies
        run: |
          pip3 install -r ./requirements.txt

      - name: run start.sh
        run: |
          bash ./start.sh

